name: flutter_real_world_example_app
description: A Demo implementation for a Real World
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  # flutter:
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^6.0.2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
