version: '3'
services:

  mongodb:
    container_name: dev_mongodb
    hostname: mongodb
    image: mongo:4.2.3
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      # - MONGO_INITDB_DATABASE=realworld
      # - MONGO_INITDB_ROOT_USERNAME=master
      # - MONGO_INITDB_ROOT_PASSWORD=letmein
      - AUTH=no
    networks:
      - devnet

  mongo-admin:
    container_name: dev_mongodb-admin
    depends_on:
      - mongodb
    hostname: mongo-admin
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    networks:
      - devnet
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017

networks:
  devnet:
    driver: bridge
